name: Deployment

on:
  workflow_dispatch:  # Manual trigger only
  # push:
  #   branches:
  #     - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Install sshpass
        run: |
          sudo apt-get update
          sudo apt-get install -y sshpass

      - name: Setup SSH key
        env:
          JUMP_HOST: ${{ secrets.JUMP_HOST }}
          JUMP_PORT: ${{ secrets.JUMP_PORT }}
        run: |
          mkdir -p ~/.ssh

          echo "${{ secrets.JUMP_PRIVATE_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa

          ssh-keyscan -p "$JUMP_PORT" "$JUMP_HOST" >> ~/.ssh/known_hosts

      - name: Deploy
        env:
          HOST: ${{ secrets.SERVER_HOST }}
          USER: ${{ secrets.SERVER_USER }}
          PASS: ${{ secrets.SERVER_PASS }}

          JUMP_HOST: ${{ secrets.JUMP_HOST }}
          JUMP_USER: ${{ secrets.JUMP_USER }}
          JUMP_PORT: ${{ secrets.JUMP_PORT }}
        run: |

          sshpass -p "$PASS" ssh \
          -o StrictHostKeyChecking=no \
          -o UserKnownHostsFile=/dev/null \
          -o ProxyCommand="ssh -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null -p $JUMP_PORT $JUMP_USER@$JUMP_HOST -W %h:%p" \
          "$USER@$HOST" << EOF

          cd /home/sdp/demos/Intel-BlueLens

          git pull origin main

          npm install

          npm run build

          EOF