name: Deployment

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Install sshpass
        run: |
          sudo apt-get update
          sudo apt-get install -y sshpass

      - name: Deploy
        env:
          HOST: ${{ secrets.SERVER_HOST }}
          USER: ${{ secrets.SERVER_USER }}
          PASS: ${{ secrets.SERVER_PASS }}
          JUMP_HOST: ${{ secrets.JUMP_HOST }}
          JUMP_USER: ${{ secrets.JUMP_USER }}
          JUMP_PASS: ${{ secrets.JUMP_PASS }}
        run: |
          sshpass -p "$PASS" ssh \
              -o StrictHostKeyChecking=no \
              -o UserKnownHostsFile=/dev/null \
              -J "$JUMP_USER@$JUMP_HOST:$JUMP_PORT" \
              "$TARGET_USER@$TARGET_HOST" << 'EOF'

          cd /home/sdp/demos/Intel-BlueLens

          git pull origin main

          npm install

          npm run build

          EOF